import Header from "@/components/Header";
import Footer from "@/components/Footer";

function Section({ id, title, children }: { id: string; title: string; children: React.ReactNode }) {
  return (
    <section id={id} className="scroll-mt-24">
      <h2 className="text-xl font-bold tracking-tight mb-4 pb-2 border-b border-foreground/10">{title}</h2>
      <div className="flex flex-col gap-4 text-sm text-foreground/80 leading-relaxed">{children}</div>
    </section>
  );
}

function Endpoint({
  method,
  path,
  description,
  request,
  response,
  note,
}: {
  method: string;
  path: string;
  description: string;
  request?: string;
  response?: string;
  note?: string;
}) {
  const methodColor =
    method === "GET"
      ? "bg-emerald-500/15 text-emerald-400 border-emerald-500/30"
      : "bg-blue-500/15 text-blue-400 border-blue-500/30";
  return (
    <div className="border border-foreground/10 rounded-xl overflow-hidden">
      <div className="px-4 py-3 bg-foreground/3 flex items-center gap-3">
        <span className={`text-xs font-mono font-bold px-2 py-0.5 rounded-full border ${methodColor}`}>
          {method}
        </span>
        <code className="text-sm font-mono text-foreground/90">{path}</code>
      </div>
      <div className="px-4 py-3 flex flex-col gap-3">
        <p className="text-sm text-foreground/70">{description}</p>
        {note && <p className="text-xs text-foreground/45 italic">{note}</p>}
        {request && (
          <div>
            <p className="text-xs text-foreground/40 mb-1 uppercase tracking-wider font-semibold">Request body</p>
            <pre className="p-3 bg-foreground/5 rounded-lg text-xs font-mono overflow-x-auto text-foreground/75 border border-foreground/10 leading-relaxed">
              {request}
            </pre>
          </div>
        )}
        {response && (
          <div>
            <p className="text-xs text-foreground/40 mb-1 uppercase tracking-wider font-semibold">Response</p>
            <pre className="p-3 bg-foreground/5 rounded-lg text-xs font-mono overflow-x-auto text-foreground/75 border border-foreground/10 leading-relaxed">
              {response}
            </pre>
          </div>
        )}
      </div>
    </div>
  );
}

function CodeBlock({ code, lang = "bash" }: { code: string; lang?: string }) {
  void lang;
  return (
    <pre className="p-4 bg-foreground/5 rounded-xl text-xs font-mono overflow-x-auto text-foreground/75 border border-foreground/10 leading-relaxed">
      {code}
    </pre>
  );
}

export default function DocsPage() {
  return (
    <div className="min-h-screen flex flex-col">
      <Header currentPath="docs" />

      <div className="flex-1 max-w-4xl mx-auto w-full px-6 pt-24 pb-12 flex gap-12">
        {/* Sidebar TOC */}
        <aside className="hidden lg:block w-48 shrink-0">
          <div className="sticky top-24 flex flex-col gap-1 text-sm">
            <p className="text-xs text-foreground/30 uppercase tracking-widest font-semibold mb-2">On this page</p>
            {[
              ["overview", "Overview"],
              ["how-it-works", "How it works"],
              ["api", "API Reference"],
              ["ai-agents", "AI Agents"],
              ["self-hosting", "Self-hosting"],
              ["open-source", "Open source"],
              ["next-steps", "Next steps"],
            ].map(([id, label]) => (
              <a
                key={id}
                href={`#${id}`}
                className="text-foreground/50 hover:text-foreground/80 transition-colors py-0.5"
              >
                {label}
              </a>
            ))}
          </div>
        </aside>

        {/* Content */}
        <main className="flex-1 min-w-0 flex flex-col gap-10">
          <div>
            <h1 className="text-3xl font-bold tracking-tight mb-2">Documentation</h1>
            <p className="text-foreground/50 text-base">
              PhyslibSearch — semantic search for the PhysLib formal physics library.
            </p>
          </div>

          <Section id="overview" title="Overview">
            <p>
              PhyslibSearch is a semantic search engine for{" "}
              <a href="https://physlib.io" target="_blank" rel="noopener noreferrer" className="underline underline-offset-2 hover:text-foreground transition-colors">
                PhysLib
              </a>
              , a formal Lean 4 physics library. It lets you find theorems, definitions, and
              instances using natural language — e.g. <em>&ldquo;Schrödinger equation&rdquo;</em> or{" "}
              <em>&ldquo;conservation of angular momentum&rdquo;</em> — without knowing the exact Lean name.
            </p>
            <p>
              The index covers <strong>9,663</strong> visible declarations across all PhysLib modules,
              each with a human-readable informal description generated by an LLM and embedded into a
              high-dimensional vector space for similarity search.
            </p>
          </Section>

          <Section id="how-it-works" title="How it works">
            <p>The pipeline has three stages:</p>
            <ol className="list-decimal list-inside flex flex-col gap-2 pl-2">
              <li>
                <strong>Informalization.</strong> Each Lean 4 declaration is translated into an informal
                mathematical description (name + explanation) by Gemini. Context such as neighboring
                declarations in the same module and type dependencies is included in the prompt to improve
                quality.
              </li>
              <li>
                <strong>Embedding.</strong> The informal description is embedded using{" "}
                <code className="font-mono text-xs bg-foreground/8 px-1 py-0.5 rounded">gemini-embedding-2-preview</code>{" "}
                (3072-dimensional cosine space) and stored in ChromaDB.
              </li>
              <li>
                <strong>Search.</strong> At query time the user&apos;s query is optionally augmented with
                HyDE (Hypothetical Document Embeddings): an LLM generates a plausible Lean 4 declaration
                that would answer the query, and that hypothetical declaration is embedded instead of the raw
                query. This aligns the query embedding with the document embedding space.
              </li>
            </ol>
          </Section>

          <Section id="api" title="API Reference">
            <p>
              Base URL:{" "}
              <code className="font-mono text-xs bg-foreground/8 px-1 py-0.5 rounded">
                http://physlibsearch.net
              </code>
              . All endpoints accept and return JSON.
              Rate limits apply: <strong>1 req/s</strong> on search, <strong>15 req/min</strong> on expand.
            </p>

            <Endpoint
              method="POST"
              path="/search"
              description="Search declarations using natural language. Accepts a batch of queries and returns a ranked list of results per query."
              request={`{
  "query": ["Newton's second law"],
  "num_results": 10          // 1–150, default 10
}`}
              response={`[
  [
    {
      "result": {
        "name": ["UnitExamples", "newtonsSecondWithDim_isDimensionallyCorrect"],
        "kind": "theorem",
        "module_name": ["UnitExamples"],
        "signature": "theorem UnitExamples.newtonsSecondWithDim_isDimensionallyCorrect ...",
        "type": "IsDimensionallyCorrect UnitExamples.NewtonsSecondWithDim",
        "informal_name": "Newton's second law F = ma is dimensionally correct",
        "informal_description": "The proposition representing Newton's second law ...",
        "docstring": null,
        "value": null
      },
      "distance": 0.276
    }
  ]
]`}
              note="Returns list[list[QueryResult]] — one inner list per input query. Sets a session cookie for feedback tracking."
            />

            <Endpoint
              method="POST"
              path="/expand"
              description="Expand a natural language query using HyDE (Hypothetical Document Embeddings). Gemini generates a plausible Lean 4 declaration that would answer the query. Pass the result to /search for better embedding alignment."
              request={`"conservation of angular momentum"`}
              response={`"theorem angularMomentumConservation {J : AngularMomentum} (h : NoExternalTorque J) : IsConserved J := ..."`}
              note="Request body is a raw JSON string (quoted). Response is a raw JSON string."
            />

            <Endpoint
              method="GET"
              path="/modules"
              description="List all PhysLib modules with their declaration counts."
              response={`[
  { "name": ["Physlib", "ClassicalMechanics", "EulerLagrange"], "count": 4 },
  { "name": ["Physlib", "Mathematics", "LinearMaps"],            "count": 38 },
  ...
]`}
            />

            <Endpoint
              method="POST"
              path="/modules/declarations"
              description="Fetch all visible declarations in a given module, in source order."
              request={`["Physlib", "ClassicalMechanics", "EulerLagrange"]`}
              response={`[
  {
    "name": ["Physlib", "ClassicalMechanics", "EulerLagrange", "eulerLagrangeEq"],
    "kind": "theorem",
    "module_name": ["Physlib", "ClassicalMechanics", "EulerLagrange"],
    "signature": "theorem Physlib.ClassicalMechanics.EulerLagrange.eulerLagrangeEq ...",
    "informal_name": "Euler–Lagrange equation",
    "informal_description": "...",
    ...
  }
]`}
            />

            <Endpoint
              method="POST"
              path="/fetch"
              description="Fetch full declaration records by Lean name. Useful for retrieving specific declarations you already know the name of."
              request={`[
  ["UnitExamples", "newtonsSecondWithDim_isDimensionallyCorrect"],
  ["Physlib", "ClassicalMechanics", "EulerLagrange", "eulerLagrangeEq"]
]`}
              response={`[ { "name": [...], "kind": "theorem", ... }, ... ]`}
            />

            <p className="text-foreground/50">Example with curl:</p>
            <CodeBlock
              lang="bash"
              code={`# Search
curl -s -X POST http://physlibsearch.net/search \\
  -H "Content-Type: application/json" \\
  -d '{"query": ["Schrödinger equation"], "num_results": 5}' | jq .

# Expand query with HyDE, then search
AUGMENTED=$(curl -s -X POST http://physlibsearch.net/expand \\
  -H "Content-Type: application/json" \\
  -d '"conservation of energy"')

curl -s -X POST http://physlibsearch.net/search \\
  -H "Content-Type: application/json" \\
  -d "{\"query\": [$AUGMENTED], \"num_results\": 5}" | jq .`}
            />
          </Section>

          <Section id="ai-agents" title="AI Agents">
            <p>
              PhyslibSearch ships a{" "}
              <a
                href="https://claude.ai/code"
                target="_blank"
                rel="noopener noreferrer"
                className="underline underline-offset-2 hover:text-foreground transition-colors"
              >
                Claude Code
              </a>{" "}
              skill that teaches any Claude agent how to call the API. Once installed, the agent can
              search Physlib, fetch declarations by name, and expand queries with HyDE — without any
              extra configuration.
            </p>
            <p className="text-foreground/50">Install the skill (one-time, any project):</p>
            <CodeBlock
              lang="bash"
              code={`mkdir -p ~/.claude/skills/physlibsearch && curl -fsSo ~/.claude/skills/physlibsearch/SKILL.md \\
  https://raw.githubusercontent.com/Kernel-Science/physlibsearch-skill/main/SKILL.md`}
            />
            <p>
              Then invoke it in any Claude Code session with{" "}
              <code className="font-mono text-xs bg-foreground/8 px-1 py-0.5 rounded">/physlibsearch</code>,
              or just ask Claude to find a Lean theorem and it will load the skill automatically.
            </p>
            <p className="text-foreground/50">
              To use it in a custom agent or system prompt, paste the raw{" "}
              <code className="font-mono text-xs bg-foreground/8 px-1 py-0.5 rounded">SKILL.md</code>{" "}
              content directly into your agent&apos;s context. The skill covers all endpoints,
              example curl calls, query tips, and how to interpret the{" "}
              <code className="font-mono text-xs bg-foreground/8 px-1 py-0.5 rounded">distance</code>{" "}
              field.{" "}
              <a
                href="https://github.com/Kernel-Science/physlibsearch-skill"
                target="_blank"
                rel="noopener noreferrer"
                className="underline underline-offset-2 hover:text-foreground transition-colors"
              >
                View on GitHub ↗
              </a>
            </p>
          </Section>

          <Section id="self-hosting" title="Self-hosting">
            <p>PhyslibSearch runs on three services:</p>
            <ul className="list-disc list-inside flex flex-col gap-1 pl-2">
              <li><strong>PostgreSQL</strong> — stores declarations, informal descriptions, and query logs</li>
              <li><strong>ChromaDB</strong> — local file-based vector store (no separate server needed)</li>
              <li><strong>FastAPI</strong> — REST API server (<code className="font-mono text-xs bg-foreground/8 px-1 py-0.5 rounded">server.py</code>)</li>
            </ul>
            <p>Required environment variables (see <code className="font-mono text-xs bg-foreground/8 px-1 py-0.5 rounded">.env.example</code>):</p>
            <CodeBlock
              code={`GEMINI_API_KEY=...          # Google AI Studio key for embeddings & LLM
CONNECTION_STRING=...       # PostgreSQL connection string
CHROMA_PATH=chroma          # Path to ChromaDB files
GEMINI_MODEL=...            # LLM model for informalization (one-time)
GEMINI_FAST_MODEL=...       # LLM model for HyDE augmentation (per query)
GEMINI_EMBEDDING_MODEL=gemini-embedding-2-preview`}
            />
            <CodeBlock
              code={`# 1. Build the index (one-time)
python -m database schema       # create PostgreSQL schema
python -m database jixia        # extract declarations with jixia
python -m database informal     # informalize with LLM
python -m database vector-db    # compute embeddings

# 2. Run the API
uvicorn server:app --host 0.0.0.0 --port 8000`}
            />
          </Section>

          <Section id="next-steps" title="Next steps">
            <ul className="list-disc list-inside flex flex-col gap-3 pl-2">
              <li>
                <strong>Continuous integration.</strong> As PhysLib grows, the database should update
                automatically when new declarations are merged. The indexing pipeline is designed to be
                incremental — each SQL step uses{" "}
                <code className="font-mono text-xs bg-foreground/8 px-1 py-0.5 rounded">ON CONFLICT DO NOTHING</code>,
                and the informalization and embedding steps skip already-processed entries — but this needs
                to be verified end-to-end for every stage before wiring up a CI workflow that triggers on
                new PhysLib commits.
              </li>
              <li>
                <strong>Index QuantumInfo.</strong> The <code className="font-mono text-xs bg-foreground/8 px-1 py-0.5 rounded">QuantumInfo</code>{" "}
                module has not been indexed yet due to integration issues between PhysLib&apos;s QuantumInfo
                dependencies and jixia. Once resolved, re-running{" "}
                <code className="font-mono text-xs bg-foreground/8 px-1 py-0.5 rounded">python -m database jixia</code>{" "}
                should pick it up incrementally without reprocessing the rest of the library.
              </li>
            </ul>
          </Section>

          <Section id="open-source" title="Open source">
            <p>
              PhyslibSearch is open source, built by{" "}
              <a href="https://kernel-science.com" target="_blank" rel="noopener noreferrer" className="underline underline-offset-2 hover:text-foreground transition-colors">
                Kernel Science
              </a>
              .{" "}
              <a
                href="https://github.com/Kernel-Science/physlibsearch"
                target="_blank"
                rel="noopener noreferrer"
                className="underline underline-offset-2 hover:text-foreground transition-colors"
              >
                View on GitHub ↗
              </a>
            </p>
            <p>The repository contains the full indexing pipeline, API server, and this frontend.</p>
            <ul className="list-disc list-inside flex flex-col gap-1 pl-2 text-foreground/70">
              <li><code className="font-mono text-xs">database/</code> — indexing pipeline (extraction, informalization, embedding)</li>
              <li><code className="font-mono text-xs">server.py</code> — FastAPI REST API</li>
              <li><code className="font-mono text-xs">engine.py</code> — ChromaDB + PostgreSQL retrieval</li>
              <li><code className="font-mono text-xs">query_expansion.py</code> — HyDE query expansion</li>
              <li><code className="font-mono text-xs">frontend/</code> — this Next.js interface</li>
            </ul>
          </Section>
        </main>
      </div>

      <Footer />
    </div>
  );
}
